### ISSUE TITLE
lecturePresenter (4.3.1314) freezes on Linux while opening a pdf document (running as root)

### ISSUE THREAD

**Issue by maxkratz** [lectureStudio/lectureStudio#6] opened 2021-03-21 11:48 UTC
**Describe the bug**
`lecturePresenter` (v4.3.1314, downloaded from the [official download page](https://www.lecturestudio.org/download) freezes while opening the demo slide set pdf from the [demo site](https://www.lecturestudio.org/demo). After the freeze, there is no way to interact with the GUI and I have to kill the process in the terminal e.g. by CTRL+C.

(On the terminal, the application only outputs some content related key words from the pdf file.)

The previous release (v4.3.1060) is able to open and show the file as expected.

**To Reproduce**
1. Download the demo slide set as pdf from: https://www.lecturestudio.org/assets/demo/overview/lectureStudio-Overview.pdf
2. Start `lecturePresenter` e.g. with `$ sudo ./lecturePresenter`
2. Click on "Dokument öffnen".
3. Choose the demo slide set pdf downloaded before.

**Expected behavior**
The application should open the pdf file and showits content.

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.1, Kernel 5.5.19-generic

**Comment by maxkratz** [comment] 2021-03-21 17:10
Update: The issue only occurs, if the application was started as user `root`. Deleting its settings in `~/.config/lectureStudio` does not fix it.

**Comment by devopvoid** [comment] 2021-04-20 18:09
Can't reproduce as of the latest release. Closing for now. Feel free to re-open, if the issue still exists with any Linux version.

@maxkratz could you please test the Linux release found [here](https://github.com/lectureStudio/lectureStudio/releases).

**Closed by devopvoid** 2021-04-20 18:09 UTC
Labels: bug, prio-critical

**Comment by maxkratz** [comment] 2021-04-22 06:45
@devopvoid The behavior shows on the newest tagged version (4.4.71), too. (At least it does on my system).

In general, from a security point of view, it does not necessarily make sense to start the application as root anyway. As far as I can see, the default settings for ports, used for streaming purposes, are outside the range that needs higher privileges on Linux. From my point of view, the issue can stay closed.
