### ISSUE TITLE
Annotations on extended slide margin not exported to pdf

### ISSUE THREAD

**Issue by elenziat** [lectureStudio/lectureStudio#37] opened 2021-04-13 10:38 UTC
lecturePresenter 4.4.44

When a slide is scaled down to extend the annotation area and the document is saved as a pdf later on, this slide is saved in its normal size without the extra margin. This means that all annotations written on the extended margin are lost.

The expected behavior is that all slides for which the annotation area is extended are saved in the smaller scale to preserve the annotations.

**Comment by devopvoid** [comment] 2021-04-13 17:15
Support for extended and zoomed slides now fixed. A new release will follow soon.

**Note the behavior**: Every time a slide has been extended or zoomed and annotated, it will be recorded with the changed view transformation.

**Comment by elenziat** [comment] 2021-04-14 07:23
I just realized that this problem was described in #30 already. I think, both issues can be closed now.

**Comment by devopvoid** [comment] 2021-04-14 07:59
Duplicate of #30

**Closed** 2021-04-14 07:59 UTC
